name: coruja
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  flutter_json_view: ^1.1.5
  font_awesome_flutter: ^10.8.0
  flutter_inappwebview: ^6.1.5
  window_size:
      git:
        url: https://github.com/google/flutter-desktop-embedding
        path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: "lib/assets/logo.png"
  web:
    generate: true
    image_path: "lib/assets/logo.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "lib/assets/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "lib/assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/logo.png
    - lib/assets/index.html
    - lib/assets/jsonViewer.js

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
